"""add BGG fields to games

Revision ID: 874c31a95c17
Revises: f3db66509e36
Create Date: 2026-09-22 20:03:47.456314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '874c31a95c17'
down_revision: Union[str, Sequence[str], None] = 'f3db66509e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('bgg_id', sa.String(length=50), nullable=True))
    op.add_column('games', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('games', sa.Column('players', sa.String(length=20), nullable=True))
    op.add_column('games', sa.Column('duration', sa.String(length=50), nullable=True))
    op.add_column('games', sa.Column('complexity', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('games', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('mechanics', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('themes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('games', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('games', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('year_published', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('min_age', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('gradient', sa.String(length=150), nullable=True))
    op.add_column('games', sa.Column('emoji', sa.String(length=16), nullable=True))
    op.create_unique_constraint('uq_games_bgg_id', 'games', ['bgg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_games_bgg_id', 'games', type_='unique')
    op.drop_column('games', 'emoji')
    op.drop_column('games', 'gradient')
    op.drop_column('games', 'min_age')
    op.drop_column('games', 'year_published')
    op.drop_column('games', 'rating')
    op.drop_column('games', 'image')
    op.drop_column('games', 'tags')
    op.drop_column('games', 'themes')
    op.drop_column('games', 'mechanics')
    op.drop_column('games', 'categories')
    op.drop_column('games', 'category')
    op.drop_column('games', 'complexity')
    op.drop_column('games', 'duration')
    op.drop_column('games', 'players')
    op.drop_column('games', 'description')
    op.drop_column('games', 'bgg_id')
    # ### end Alembic commands ###
