"""create matches and link tables to logged match

Revision ID: f3db66509e36
Revises: bf42119a9de7
Create Date: 2026-09-22 14:50:07.058960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3db66509e36'
down_revision: Union[str, Sequence[str], None] = 'bf42119a9de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('logged_by_id', sa.UUID(), nullable=False),
    sa.Column('participant_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('is_tie', sa.Boolean(), nullable=False),
    sa.Column('tied_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_group_win', sa.Boolean(), nullable=False),
    sa.Column('group_win_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('photo_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['logged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['game_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_tables', sa.Column('logged_match_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_game_tables_logged_match_id_matches', 'game_tables', 'matches', ['logged_match_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_game_tables_logged_match_id_matches', 'game_tables', type_='foreignkey')
    op.drop_column('game_tables', 'logged_match_id')
    op.drop_table('matches')
    # ### end Alembic commands ###
